cmake_minimum_required(VERSION 3.21)

include(FetchContent)
set(FETCHCONTENT_QUIET off)

set(FETCHCONTENT_BASE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/_external)

include(cmake/fetch_external/miniz.cmake)
include(cmake/fetch_external/simdjson.cmake)
include(cmake/fetch_external/fmt.cmake)
include(cmake/fetch_external/SDL.cmake)
include(cmake/fetch_external/ImGui.cmake)
include(cmake/fetch_external/bgfx.cmake)
include(cmake/fetch_external/glm.cmake)
include(cmake/fetch_external/spdlog.cmake)
include(cmake/fetch_external/nlohmann_json.cmake)
include(cmake/fetch_external/fastgltf.cmake)
include(cmake/fetch_external/picosha2.cmake)
include(cmake/fetch_external/cpr.cmake)
include(cmake/fetch_external/tiny-process-library.cmake)
include(cmake/fetch_external/wpilib.cmake)
include(cmake/fetch_external/argparse.cmake)